version: '2'

services:
  ci-unit-tests:
    image: microsoft/dotnet:1.1.2-sdk
    container_name: unittests
    volumes:
     - .:/src
    working_dir: /src
    command: sh ./deploy/scripts/run-unit-tests.sh
