version: '2'

services:
  ci-build:
    image: microsoft/aspnetcore-build:1.0-1.1
    container_name: build
    volumes:
     - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./FeatureToggleApi.sln && dotnet publish ./FeatureToggleApi.sln -c Release -o ./build"