version: '2'

services:
  ftm:
    container_name: ftm
    image: ftm
    build:
      context: ./src/Presentation.API
      dockerfile: Dockerfile
      args:
        source: ./build
    ports:
      - "5000:80"        
  # neo4j:
    # image: neo4j
    # restart: unless-stopped

    # ports:
      # - 7473:7473
      # - 7474:7474
      # - 7687:7687

    # volumes:
      # - "./import:/import"
      # - "./plugins:/plugins"
      # - "./data:/data"
  # zookeeper:
    # image: wurstmeister/zookeeper
    # ports:
      # - "2181:2181"
  # kafka:
    # image: wurstmeister/kafka
    # ports:
      # - "9092:9092"
    # environment:
      # KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      # KAFKA_CREATE_TOPICS: "test:1:1"
      # KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      # KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    # volumes:
      # - /var/run/docker.sock:/var/run/docker.sock